version: "3.0"

volumes:
  mongodb:

networks:
  mongo:
    driver: bridge

services:
  mongo-primary:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    env_file:
      ./.env.development
    ports:
      - 27017:27017
    command: 'mongod --auth'

    networks:
      mongo:
    restart: always
