export { create } from './controllers/Create.method'
export { login } from './controllers/Login.method'
export { list } from './controllers/List.method'
export { updateInfo } from './controllers/UpdateInfo.method'
export { find } from './controllers/Find.method'
export { deactivate } from './controllers/Deactivate.mehtod'
